language: python
python:
  - "3.4"
# command to install dependencies
install: 
    - "pip install -r requirements.txt"
    - "pip install flake8"
# command to run tests 
script: 
    - "python manage.py test"
after_script:
    - "flake8 jaumt --max-line-length=99 --exclude='jaumt/migrations'"
